### ISSUE TITLE
Problem: Qt platform plugin "windows" can not loaded when using opencv highgui functions

### ISSUE THREAD

**Issue by argltuc** [conda-forge/opencv-feedstock#229] opened 2020-04-24 10:12 UTC
Issue:
I built a small c++ testing application on Windows 10 / Visual Studio 2019 which create a cv::mat, fill it with a chess board and show it with cv::imshow. When calling cv::imshow the following error appears:
`qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

I figure out one "workaround": adding a environment variable "QT_PLUGIN_PATH" pointing to "<miniconda_root>/Library/plugins" will disapear the error, but result in opening a window for cv::imshow, which is not correct configured and showing to content (even black image, which is not the content or size of my created cv::mat)... so it's not a solution, since i will display some matrix content with cv::imshow.

My miniconda installation is in $PATH, cmake is part of my system setup.

If any information to solve ths issue is missing, give me a hint.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# Name                    Version                   Build  Channel
argcomplete               1.11.1                     py_0    conda-forge
brotlipy                  0.7.0           py37h4ab8f01_1000    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37ha419a9e_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.6.0            py37h702c6c1_2    conda-forge
console_shortcut          0.1.1                         4
cryptography              2.8              py37hb32ad35_1    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
git                       2.26.2                        0    conda-forge
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
intel-openmp              2020.0                      166
jpeg                      9c                hfa6e2cd_1001    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libclang                  9.0.1           default_hf44288c_0    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
liblapacke                3.8.0                    15_mkl    conda-forge
libopencv                 4.2.0                    py37_6    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp                   1.0.2                hfa6e2cd_5    conda-forge
lz4-c                     1.9.2                h33f27b4_0    conda-forge
menuinst                  1.4.16                   py37_0    conda-forge
mkl                       2020.0                      166
numpy                     1.18.1           py37h90d3380_1    conda-forge
opencv                    4.2.0                    py37_6    conda-forge
openssl                   1.1.1g               he774522_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
powershell_shortcut       0.0.1                         3
py-opencv                 4.2.0            py37h43977f1_6    conda-forge
pycosat                   0.6.3           py37h8055547_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pywin32                   227              py37hfa6e2cd_0    conda-forge
qt                        5.12.5               h7ef1ec2_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
ruamel_yaml               0.15.80         py37h8055547_1001    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tqdm                      4.45.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
yaml                      0.2.4                he774522_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                h9f78265_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : base
    active env location : C:\Users\argl\Tools\dev\Miniconda3
            shell level : 1
       user config file : C:\Users\argl\.condarc
 populated config files : C:\Users\argl\Tools\dev\Miniconda3\.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\argl\Tools\dev\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\argl\Tools\dev\Miniconda3\pkgs
                          C:\Users\argl\.conda\pkgs
                          C:\Users\argl\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\argl\Tools\dev\Miniconda3\envs
                          C:\Users\argl\.conda\envs
                          C:\Users\argl\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by hmaarrfk** [comment] 2020-04-24 14:05
man, welcome to windows development hell. I went through this a while back.

I'm really not sure you can configure it to use the conda install super well.

Do you use cmake?

I think the strategy is:

1. Open an anaconda prompt
2. Activate your environment.
3. Start whatever build system you use from the prompt

You may need to install some "compilers" for windows so that it sets the compiler environment variables correctly.

**Comment by argltuc** [comment] 2020-04-24 15:28
I don't think thats the build enviroment itself is the problem.
I'm alread in activated base environment and building my application works fine. I can also running it, if i don't use any highgui calls.

I think the point is more the interaction of opencv_highgui.dll with Qt (and maybe Qt with it's own configuration in conda).

So from my point of view, i'm not sure, if it is a problem how opencv is build against Qt or if it is a problem how Qt package is configured during conda install (in ths case it will be an issue for the qt5 feedstock).

**Comment by hmaarrfk** [comment] 2021-01-05 20:34
Sorry for taking so long to reply.

I think that opencv on windows is correctly compiled. Otherwise, the compiler would have complained. At least, that is my theory.

I haven't used opencv+ qt on windows for a while. Do you have example code that might be able to confirm that it is problematic (beyond you trying to compile something new in VS2019?)

**Comment by hmaarrfk** [comment] 2023-11-10 20:35
closing due to lack of reproducing example.

We can reopen if the issue resurfaces.

Sorry for taking too long to reply.

**Closed by hmaarrfk** 2023-11-10 20:35 UTC
