### ISSUE TITLE
can't find libpng, libjpeg, and libtiff

### ISSUE THREAD

**Issue by zym1010** [conda-forge/opencv-feedstock#19] opened 2016-07-06 01:33 UTC
When trying to compile a minimal example for OpenCV (<http://docs.opencv.org/2.4/doc/tutorials/introduction/display_image/display_image.html>) on a CentOS 6.2 machine, I encountered some linking issue (initially, same thing happened when compiling Caffe).

~~~
[yimengzh@psych-o ~]$ IFOLDER=~/miniconda2/envs/cafferc3/include
[yimengzh@psych-o ~]$ LFOLDER=~/miniconda2/envs/cafferc3/lib
[yimengzh@psych-o ~]$ g++ test-opencv.cpp -I${IFOLDER} -L${LFOLDER} -lopencv_core -lopencv_highgui -lopencv_imgproc
/usr/bin/ld: warning: libjpeg.so.9, needed by /home/yimengzh/miniconda2/envs/cafferc3/lib/libopencv_highgui.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libpng16.so.16, needed by /home/yimengzh/miniconda2/envs/cafferc3/lib/libopencv_highgui.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtiff.so.5, needed by /home/yimengzh/miniconda2/envs/cafferc3/lib/libopencv_highgui.so, not found (try using -rpath or -rpath-link)
~~~

However, `ldd` the `libopencv_highgui.so` looks good.

~~~
[yimengzh@psych-o ~]$ ldd /home/yimengzh/miniconda2/envs/cafferc3/lib/libopencv_highgui.so
	linux-vdso.so.1 =>  (0x00007ffff6067000)
	libopencv_imgproc.so.2.4 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libopencv_imgproc.so.2.4 (0x00002b69479f0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b6947ebb000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b69480bf000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b69482dc000)
	libz.so.1 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libz.so.1 (0x00002b69484e5000)
	libjpeg.so.9 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libjpeg.so.9 (0x00002b6948700000)
	libpng16.so.16 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libpng16.so.16 (0x00002b694893c000)
	libtiff.so.5 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libtiff.so.5 (0x00002b6948b7d000)
	libjasper.so.1 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libjasper.so.1 (0x00002b6948e0b000)
	libopencv_core.so.2.4 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libopencv_core.so.2.4 (0x00002b694907e000)
	libstdc++.so.6 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libstdc++.so.6 (0x00002b69494c0000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b694987c000)
	libgomp.so.1 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libgomp.so.1 (0x00002b6949b00000)
	libgcc_s.so.1 => /home/yimengzh/miniconda2/envs/cafferc3/lib/./libgcc_s.so.1 (0x00002b6949d24000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b6949f3b000)
	/lib64/ld-linux-x86-64.so.2 (0x00000032ef400000)
	liblzma.so.5 => /home/yimengzh/miniconda2/envs/cafferc3/lib/././liblzma.so.5 (0x00002b694a2d0000)
~~~

I can work around it by using `rpath`, but I wonder if this is the case in general, as I think specifying `-L` and `-I` should do. 

I tried the same program in a vagrant ubuntu 14.04 box, and similar things happened. This time, complaint about `libtiff` disappeared, but those for `libpng` and `libjpeg` still exists.

**Comment by jakirkham** [comment] 2016-07-06 04:35
Could you please do `conda list` for that environment?

**Comment by zym1010** [comment] 2016-07-06 12:29
@jakirkham 

I believe my problem is true in general. This is my understanding of it.

1. `libopencv_highgui.so` has to find `libtiff `, `libpng`, etc.
2. They don't exist in 'standard' locations, but in a conda environment's `lib`.
3. When linking my program, result in `ldd libopencv_highgui.so` doesn't matter, as that is what will be linked when the main executable is `libopencv_highgui.so` itself, not when linking against it (not sure if this is true, but seems to be the case by my experiment).

According to this, after adding `export LD_LIBRARY_PATH=${LFOLDER}`, the program compiled successfully.

Below is a listing of conda-related things for my vagrant box.
~~~
(opencv)vagrant@vagrant-ubuntu-trusty-64:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.0.10
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/vagrant/miniconda2  (writable)
  default environment : /home/vagrant/miniconda2/envs/opencv
     envs directories : /home/vagrant/miniconda2/envs
        package cache : /home/vagrant/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

(opencv)vagrant@vagrant-ubuntu-trusty-64:~$ conda list
# packages in environment at /home/vagrant/miniconda2/envs/opencv:
#
blas                      1.1                    openblas    conda-forge
jasper                    1.900.1                       2    conda-forge
jpeg                      9b                            0    conda-forge
libgfortran               3.0.0                         1    defaults
libpng                    1.6.23                        0    conda-forge
libtiff                   4.0.6                         5    conda-forge
numpy                     1.11.0          py27_blas_openblas_201  [blas_openblas]  conda-forge
openblas                  0.2.18                        2    conda-forge
opencv                    2.4.12              np111py27_2    conda-forge
openssl                   1.0.2h                        1    defaults
pip                       8.1.2                    py27_0    defaults
python                    2.7.12                        1    defaults
readline                  6.2                           2    defaults
setuptools                23.0.0                   py27_0    defaults
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py27_0    defaults
xz                        5.0.5                         1    conda-forge
zlib                      1.2.8                         3    conda-forge
~~~

**Comment by patricksnape** [comment] 2016-07-07 08:22
Yes, in general conda built packages are only really useful if built within a conda environment. You likely need to manually set the rpath for your program build in order to ensure the deps are resolved consistently.

**Comment by zym1010** [comment] 2016-07-07 13:37
@patricksnape  thanks!

**Comment by zym1010** [comment] 2016-07-07 13:38
I feel it would be better to write this trick down somewhere, since people expect to use conda packages as those installed by sudo...

**Comment by jakirkham** [comment] 2016-07-07 14:17
So, my normal recommendation is if you want to build with a conda environment do the following.

1. Write a recipe.
2. Build with `conda-build`.
3. Install the resulting package in an environment.

Take a look at the [docs]( http://conda.pydata.org/docs/building/build.html ) to get a feel for how to do this. Please feel free to ask questions.

Also, I do have a [recipe for `caffe`]( https://github.com/conda-forge/caffe-feedstock ), which you may want to try. Unfortunately all the goodies (e.g. CUDA and cuDNN) have restrictive licensing. So I can't distribute them to you or at least don't know how to legally. Though we are trying to get info from NVIDIA about how that might be done. In the meantime, you could try building it locally with `conda-build` and some tweaks to enable and look for those goodies.

In any event, I think this question does not pertain to how OpenCV builds so am closing this. Feel free to keep asking questions on it though.

**Closed by jakirkham** 2016-07-07 14:17 UTC

**Comment by zym1010** [comment] 2016-07-07 14:53
@jakirkham  thanks.

> Also, I do have a recipe for caffe, which you may want to try. 

GPU is the reason I need to compile Caffe on my own.

> In any event, I think this question does not pertain to how OpenCV builds so am closing this. Feel free to keep asking questions on it though.

So basically, you and @patricksnape are suggesting that to use conda libraries as those system-wide ones, some hacking might be needed, right?

**Comment by jakirkham** [comment] 2016-07-07 14:59
@jakirkham  thanks.

> > Also, I do have a recipe for caffe, which you may want to try. 

> GPU is the reason I need to compile Caffe on my own.

Of course, which I fully understand. Hence my suggestion to use that recipe to get things going and tweak for CUDA and cuDNN support. Then build it yourself locally with `conda-build`.

Most of the trouble with Caffe is the dependencies, which we have handle for you.

>> In any event, I think this question does not pertain to how OpenCV builds so am closing this. Feel free to keep asking questions on it though.

> So basically, you and @patricksnape are suggesting that to use conda libraries as those system-wide ones, some hacking might be needed, right?

No hacking needed. Really try using the Caffe recipe to do the build locally. Just let me know if you run into issues with that. Maybe we should move this discussion over there. 😉 Up to you.

**Comment by jakirkham** [comment] 2016-07-07 15:15
While I see what you are say, interestingly I would argue that it is easier, cleaner, and more reproducible to have a conda package.

Why you may ask? It turns out there are all sorts of nifty ways to encode what dev version of package you built from like what branch, which commit, how many commits since the last release, etc. This let's you track which development version you are using in an environment. Also, as each conda package is built in a totally clean environment you don't need to worry about it getting affected by pieces of other builds (e.g. old object files).

Most people I know have dev recipes for the reasons mentioned above. Take a look at this [example]( https://github.com/conda-forge/conda-smithy/blob/09a58ef776b003eb4f24cf6ced8ea81e448dbd85/conda_smithy.recipe/meta.yaml#L5 ) from `conda-smithy`. Also, here is an example from one of my own development [recipes]( https://github.com/nanshe-org/rank_filter/blob/94b783fbaf20c853b1bec1b64ecfdbaea5d7fb1a/rank_filter.recipe/meta.yaml#L3 ). Also, `conda-build` does this [itself]( https://github.com/conda/conda-build/blob/bc3ea7dd62e2f343c5746668ee2cce91a7eed333/conda.recipe/meta.yaml#L3-L12 ). Finally, `pandas` does [this]( https://github.com/pydata/pandas/blob/2655daef1b7346feabd00d4d40910a80386d0812/conda.recipe/meta.yaml#L3-L8 ).
