### ISSUE TITLE
Windows build fails for a library which depends on OpenCV

### ISSUE THREAD

**Issue by show0k** [conda-forge/opencv-feedstock#167] opened 2019-07-09 09:49 UTC
I'm trying to build a recipe of [Aruco](https://github.com/conda-forge/aruco-feedstock), a C++ library which depends on OpenCV.
I've troubles for the compilation on Windows ([link of the CI log](https://ci.appveyor.com/project/conda-forge/aruco-feedstock/builds/25827938)).
```
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration
```
It seems like the CI environment is not the same as the one it was built on. But, both are conda-smithy generated pipelines and use only x86-64 processors and Visual Studio 14 2015 as a compilator.
As found on other issues, I already explicitly specify to use a x64 compilation with` cmake -G "Visual Studio 14 2015 Win64"                                                                   `
Does someone already experienced that issue ?

**Comment by mshabunin** [comment] 2019-07-10 14:23
Did it work at some moment or you are trying to implement it from scratch?

OpenCV on Windows platform uses different layout from the one used by conda, try to set `OpenCV_DIR` and/or `OpenCV_LIB_PATH` cmake option to `<root>/Library/lib`. Probably modifiyng OpenCV cmake package will be required to fix it.

**Comment by carterbox** [comment] 2019-07-11 14:18
This might be a duplicate of #41.

**Closed** 2019-07-22 21:09 UTC
