### ISSUE TITLE
highgui functions not working - could not find/load Qt plugin "xcb"

### ISSUE THREAD

**Issue by 0phoff** [conda-forge/opencv-feedstock#97] opened 2017-12-05 15:18 UTC
Hey,

I installed opencv in a docker image, using your feedstock.
Everything seems to be working except the gui functionality...
Whenever I run cv2.imshow('img', img) it gives this error:  
```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)
```

Let me know if you need more information
Any help is appreciated!

---

Here are some details about my dockerfile:
```Docker
FROM nvidia/cuda:8.0-cudnn7-devel

# Install deps
RUN apt-get .... 

# Installing anaconda
RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh && \
    wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh -O anaconda.sh && chmod +x anaconda.sh &&\
    ./anaconda.sh -b -p /opt/conda
ENV PATH /opt/conda/bin:$PATH

# Setting conda env
....

# Install opencv
RUN conda install -c conda-forge opencv
```
---

Inside Docker:
```bash
$ python --version
Python 3.6.2 :: Continuum Analytics, Inc.
$ conda --version
conda 4.3.30
$ conda list opencv
opencv             3.3.0      py36_blas_openblas_202  [blas_openblas]  conda-forge
```

**Comment by jakirkham** [comment] 2017-12-05 15:25
As it uses Qt, would recommend installing these [yum requirements]( https://github.com/conda-forge/qt-feedstock/blob/2156001d34bb26448ff187537b013d6d340432e7/recipe/yum_requirements.txt ) for Qt. Since this is in Docker, one will likely need to do some work to get X11 port forwarding setup between the Docker container and the native OS.

**Comment by 0phoff** [comment] 2017-12-05 15:30
Yeah I temporarily disable access control with `xhost +`...  
I know its an ugly solution, but I will search for a beter one, after I get everything to work properly.. :clown_face: 

You dont happen to have an apt requirements file? Guess Ill have to find the matching packages...

**Comment by jakirkham** [comment] 2017-12-05 16:03
FWIW I found [these examples]( http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/ ) somewhat helpful when playing with something similar. Though I'm sure you have probably already read similar things.

We build on CentOS 6. So the `yum_requirements.txt` files are not so much recommendations as exactly what we install during the build. Normally can switch `devel` to `dev` and most things then work on Ubuntu, but there might be a few other things to switch. Typically a quick Google resolves these.

**Comment by jakirkham** [comment] 2017-12-05 16:07
Ultimately we do want to get rid of `yum_requirements.txt`. So this should be less of an issue over time. For instance we have all the `conda` packages needed for X11. There is a WIP `gtk2` package in the works. Also we have most interpreters at this point `python`, `perl`, `ruby`, etc. We just need to finish these things up and start making use of them.

**Comment by 0phoff** [comment] 2017-12-05 17:12
Yeah, I already found all the packages for aptitude, I will try  rebuilding my docker container tomorrow. I'll let you know whether it worked out or not! :)

**Comment by jakirkham** [comment] 2017-12-05 17:16
Sure that last comment is more discussing a longer term project. Ok, best of luck.

**Comment by 0phoff** [comment] 2017-12-07 08:45
I installed all the `yum_requirements.txt` in my image and then rebuild everything, but still have the same error
```bash
# Install command
# Only package not installed is 'xorg-x11-server-Xvfb' as I do not want a fake X-server
apt-get install -y libx11-dev libxt-dev libxext-dev chrpath libxrender-dev python-dbus-dev libsm-dev libice-dev pkg-config libgtk2.0-dev ruby &&\
```
Since it was complaining about the xcb plugin for qt, I went looking for a package for that plugin and found the `libx11-xcb1` package, so I also installed that one.  
Now I am getting a new error... Huray!  :weary: 
```bash
process 67: The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted (core dumped)
```

@jakirkham thanks for the link to the docker guide, I had already found it and was planning to do something like that :smile:  
To rule out an error with my X forwarding, I went ahead and implemented that new user thing, and I can fire up firefox from inside that docker container fine. So the problem is really related to python-opencv/qt...

**Comment by jakirkham** [comment] 2017-12-10 16:09
It seems the `qt` package has `dbus` in both `yum_requirements.txt` and ``meta.yaml`. That muddies the waters a bit. Could you please raise an [issue with the `qt` maintainers]( https://github.com/conda-forge/qt-feedstock/issues ) about this?

**Comment by jakirkham** [comment] 2017-12-10 16:13
Also might want to ask the [`dbus` maintainers]( https://github.com/conda-forge/dbus-feedstock/issues ) about getting the `-rdynamic` flag added to aid debugging problems like this one.

**Comment by jakirkham** [comment] 2018-02-19 02:07
Is this still a problem, @0phoff?

**Comment by 0phoff** [comment] 2018-06-06 09:57
Oh, sorry I completely forgot about this issue.

Well, I personally got around the problem by just using the pip version of opencv, but that does not mean this issue is fixed... This does mean I might not get all out of my system when using opencv through python, as the build process was not optimized for my setup. _(or at least, that's what I think and one of the reasons I wanted to give conda a try :innocent:)_

So for anyone having this problem:
```bash
pip install opencv-python
```
---
For my part, you can close this issue, unless this is something you want to track down and fix anyway! :slightly_smiling_face:

**Comment by hajapy** [comment] 2018-08-04 16:12
Closing - the issue is linked in CFEP 04, so the context can always be retrieved, but there is nothing for us to fix here.

**Closed by hajapy** 2018-08-04 16:12 UTC

**Comment by jakirkham** [comment] 2018-08-04 17:14
We can of course just add the X11 dependencies. Many packages have done this already.
