### ISSUE TITLE
cv2.VideoCapture not working

### ISSUE THREAD

**Issue by cailiang9** [conda-forge/opencv-feedstock#73] opened 2017-05-19 05:25 UTC
wget https://github.com/opencv/opencv_extra/raw/master/testdata/highgui/video/VID00003-20100701-2204.avi
/conpy3/bin/python test_ffmpeg.py
cap = cv2.VideoCapture('VID00003-20100701-2204.avi')
print(cap.read())

The output is:
Unable to stop the stream: Inappropriate ioctl for device
(False, None)

ldd cv2.so can find all so dependencies. But strangely no libv4l.so in the list.

**Comment by jakirkham** [comment] 2017-05-19 06:31
We don't build with v4l-utils currently. So I wouldn't expect it to work. That said, if this is a question of adding it, we can certainly discuss it, but I think it would require adding a `v4l-utils` package to conda-forge. Is that something you would be willing to do?

**Comment by cailiang9** [comment] 2017-05-19 06:58
I don't know more details. I was told ffmpeg already supported. Are these ffmpeg functions?

**Comment by jakirkham** [comment] 2017-05-19 17:06
FWICT `ffmpeg` says `v4l2` support is enabled and built in the [latest build log]( https://circleci.com/gh/conda-forge/ffmpeg-feedstock/79 ). Not sure how it does this without the libraries available. However that is not part of `ffmpeg`. I'm pretty sure we still need `libv4l` and `v4l-utils` built and packaged for `conda`.

Though you could try a hack and install them with your system package manager. Might work, but no promises. And as usual we are **not** responsible if something horrible happens to your system.

**Comment by sdvillal** [comment] 2017-05-27 15:15
After talking with a colleague of mine that is an opencv guru, and banging my own head against the wall by building myself a [conda v4l-utils](https://anaconda.org/loopbio/v4l-utils) package (with minimal features), I think blaming this on v4l, depite all the noise around the internet, is a red-herring. Instead, I hope the next opencv package release (#75) will have it fixed.

(Let me know if you ever need that vl4-utils recipe though).

**Comment by patricksnape** [comment] 2017-05-27 19:40
This should be fixed now since that test passed in #75. So please confirm it's fixed (in about 2 hours) and then we can close this

**Closed** 2017-05-30 03:18 UTC

**Comment by QuantScientist** [comment] 2019-08-24 09:52
Dear team,
I have this exact same issue using docker:

```
RUN conda config --add channels conda-forge
RUN conda install -c conda-forge ffmpeg x264
RUN conda install -c conda-forge opencv
```
Result:

> Unable to stop the stream: Inappropriate ioctl for device
> cannot open video
> 

Am I missing something?

**Comment by hmaarrfk** [comment] 2019-08-24 12:02
Could you open a new issue with the full docker file that reproduces the issue

**Comment by mshabunin** [comment] 2019-08-26 12:11
> Could you open a new issue with the full docker file that reproduces the issue

And minimal script reproducing the issue (ideally with problematic video file).

**Comment by QuantScientist** [comment] 2019-08-26 18:09
Yes, of course:
https://github.com/QuantScientist/DarkTorch
https://github.com/QuantScientist/DarkTorch/blob/master/docker/Dockerfile

Thanks,

**Comment by QuantScientist** [comment] 2019-08-26 19:05
Thank you so much for the detailed response. I have no restrictions regarding ffmpeg, I would use any version that works with that specific OpenCV version (e.g. 3.4.1) since it is the only thing that links correctly against Libtorch ABI. 

I am willing to use any other combination of OpenCV / ffmpeg that you recommend using. 
I already experimented heavily with compiling OpenCV on my own having spent several days on multiple versions of torch / opencv / ffmpeg.
