### ISSUE TITLE
The function not implemented error

### ISSUE THREAD

**Issue by bishesh** [conda-forge/opencv-feedstock#87] opened 2017-07-20 16:35 UTC
I installed opencv in a conda venv using: `conda install opencv -c conda-forge`
I have libgtk2.0-dev and pkg-config installed in my ubuntu system.
However, trying to use opencv functions such as `cv2.imshow()` does not work and gives an error (below). 
The opencv videowriter also returns an error saying that it cannot be opened.

```
error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/highgui/src/window.cpp:583: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage
```

**Comment by jakirkham** [comment] 2017-07-20 18:55
This seems like a duplicate of issue ( https://github.com/conda-forge/opencv-feedstock/issues/43 ).

Unfortunately having GTK on your system is not enough, we would actually need to build the package with GTK support on our end. However there is no GTK package in `defaults` or `conda-forge` yet. So we are unable to do this.

That said, we do build Qt support on some platforms or use the OS provided visualization libraries on others. Would double check that you have the latest `opencv` build (version `3.2.0` build number `204`). If that still doesn't work, please provide the results of `conda info` and `conda env export` from the affected environment.

**Comment by bishesh** [comment] 2017-07-21 09:36
The opencv version is 3.2.0. How do I check the build number ? All other information are below:

`conda list | grep opencv`:
`opencv                    3.2.0               np112py36_0    conda-forge`

`conda info`:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.10
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/bk17/anaconda3  (writable)
    default environment : /home/bk17/anaconda3/envs/pytorch
       envs directories : /home/bk17/anaconda3/envs
                          /home/bk17/.conda/envs
          package cache : /home/bk17/anaconda3/pkgs
                          /home/bk17/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.12.4 CPython/3.6.0 Linux/4.8.0-58-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1001:1001
```
`conda env export`:

```
name: pytorch
channels:
- local
- conda-forge
- soumith
- defaults
dependencies:
- cairo=1.14.6=4
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- giflib=5.1.4=0
- glib=2.51.4=0
- graphviz=2.38.0=4
- harfbuzz=1.3.4=2
- hdf5=1.8.17=11
- icu=58.1=1
- jasper=1.900.1=4
- libpng=1.6.28=0
- libwebp=0.5.2=7
- matplotlib=2.0.2=np112py36_0
- opencv=3.2.0=np112py36_0
- pango=1.40.3=3
- pillow=4.1.1=py36_0
- qt=5.6.2=3
- bleach=1.5.0=py36_0
- cffi=1.9.1=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- expat=2.1.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- html5lib=0.999=py36_0
- ipykernel=4.6.1=py36_0
- ipython=6.0.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jbig=2.1=0
- jinja2=2.9.6=py36_0
- jpeg=9b=0
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.0.1=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libtool=2.4.2=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=0.23=py36_2
- mistune=0.7.4=py36_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py36_0
- nbformat=4.3.0=py36_0
- networkx=1.11=py36_0
- notebook=5.0.0=py36_0
- numpy=1.12.1=py36_0
- olefile=0.44=py36_0
- openssl=1.0.2k=1
- pandocfilters=1.4.1=py36_0
- path.py=10.3.1=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- pycparser=2.17=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=0
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np112py36_0
- pyzmq=16.0.2=py36_0
- qtconsole=4.3.0=py36_0
- readline=6.2=2
- scikit-image=0.13.0=np112py36_0
- scikit-learn=0.18.1=np112py36_1
- scipy=0.19.0=np112py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.18=0
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- simpleitk=your_custom_version=py36_0
- cuda80=1.0=0
- pytorch=0.1.12=py361_2cu80
- torchvision=0.1.8=py36_2
- pip:
  - backports.weakref==1.0rc1
  - certifi==2017.4.17
  - chardet==3.0.4
  - idna==2.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - jupyterthemes==0.16.4
  - lesscpy==0.12.0
  - markdown==2.2.0
  - nibabel==2.1.0
  - nilearn==0.3.0
  - pandas==0.20.2
  - ply==3.10
  - prompt-toolkit==1.0.14
  - protobuf==3.3.0
  - requests==2.18.1
  - seaborn==0.7.1
  - tensorflow==1.2.0
  - torch==0.1.12.post2
  - urllib3==1.21.1
  - visdom==0.1.4
  - werkzeug==0.12.2
prefix: /home/bk17/anaconda3/envs/pytorch
```

**Closed** 2017-12-02 18:13 UTC
